### ISSUE TITLE
Flow error: /angular.js:2:35,39:  Incorrect number of type parameters (expected 1)

### ISSUE THREAD

**Issue by 0xR** [solnetdigital/flow-interfaces-angular#2]
I am running flow 0.10.0 and I get the following error:

```
./app/bower_components/flow-interfaces-angular/interfaces/angular.js:2:35,39: 
Incorrect number of type parameters (expected 1)

some-controller.js:4:1,31: call of method module
Function cannot be called on
  ./app/bower_components/flow-interfaces-angular/interfaces/angular.js:42:3,8: AngularJS
```

My controller looks like this:

``` javascript
/*@flow */
'use strict';

angular.module('someModule')
.controller(function(){

  });
```

This makes `flow-interfaces-angular` unusable for me.

**Comment by faceleg** [comment]
I agree, I think this issue: https://github.com/facebook/flow/issues/199 is related

**Comment by 0xR** [comment]
You have opened this issue yourself on 18 Dec 2014. Am I correct in assuming that `flow-interfaces-angular` didn't work since then? Could you maybe put some sort of warning in the Readme? Now it promises a working interface while it doesn't work.

**Comment by faceleg** [comment]
Done. 

I'll leave this open until https://github.com/facebook/flow/issues/199 is fixed.

**Comment by 0xR** [comment]
:+1:

**Comment by faceleg** [comment]
Feel free to comment on the flow issue asking for an update!
